=== JuanValencia19/Parcial2/Punto 4/empleados.dtd
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (id, nombre, edad, departamento)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>

=== JuanValencia19/Parcial2/Punto 4/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "empleados.dtd">
<empleados>
    <empleado>
        <id>1</id>
        <nombre>Juan Perez</nombre>
        <edad>30</edad>
        <departamento>Recursos Humanos</departamento>
    </empleado>
    <empleado>
        <id>2</id>
        <nombre>María Gómez</nombre>
        <edad>27</edad>
        <departamento>Contabilidad</departamento>
    </empleado>
</empleados>
